repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: local
    hooks:
      - id: lint-imports
        name: lint-imports
        entry: python3 scripts/lint_imports.py
        language: system
        files: \.py$
        pass_filenames: false
